### PR TITLE
Restructure the project into packages and fix BLEU scoring.

### PR DESCRIPTION
**Pull request by m5w**
Also make training deterministic and automate testing (on my computer...I'll generalize the script soon.)

### CODE REVIEW

**Comment by m5w** [comment]
@bujol12 I had to make all your import statements relative, so please make sure this doesn't break anything.

**Comment by m5w** [comment]
Because of some newer commits, this also adds projectivization. Use the ``--projectivise`` argument on both the trainer and linearizer to use it.

**Comment by bujol12** [comment]
@m5w ,

it does break my program.... I'll have a look at it later.

**Comment by m5w** [comment]
I believe I've fixed the imports.

**Pull request merged**
